project:
  type: website
  output-dir: docs

jupyter: python3

lang: en

website:
  title: "Marcel Maré"
  favicon: images/favicon.png
  site-url: https://marcelmare.com
  open-graph: true
  # google-analytics: "G-3N2FL85753"
  search:
    location: sidebar
    type: overlay

  navbar:
    logo: /images/logo.png
    title: "ARCEL MARÉ"
    pinned: false
    collapse-below: md

  sidebar:
    style: docked  
    collapse-level: 1
    background: light

    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/marem1969/
        text: "LinkedIn"
      - icon: instagram
        href: https://www.instagram.com/in/marem1969/
        text: "Instagram"
      - icon: substack
        href: https://spottedape.substack.com
        text: "RSS feed"

    contents:
      - text: "Essays"
        href: posts/substack/index.qmd
      - section: "Portfolio"
        href: portfolio/index.qmd
        contents:
          - text: "Creative x AI Workshops"
            href: portfolio/creative-x-ai-workshops.qmd
          - text: "Sibabalwe Bakery"
            href: portfolio/sibabalwe-bakery.qmd
          - text: "Momentum Recharge"
            href: portfolio/momentum-recharge.qmd
          - text: "Vantage HIV"
            href: portfolio/vantage-hiv.qmd
          - text: "Remote Real-Time Digital Video"
            href: portfolio/csir-remote-video.qmd
          - text: "Veza Tourism"
            href: portfolio/csir-veza-tourism.qmd
      - text: "About Me & Contact"
        href: index.qmd#about-me
      - text: "Book an appointment"
        href: appointment/index.qmd
  page-footer:
    left: |
      <br>
       __Marcel Maré__
      <br>
      &copy; 2026
    center: |
      <br>
      <br>
      <br>
    right: |
      <br>
      
      <br>
      <br>
      <br>

format:
  html:
    # page-layout: full
    date-format: "MMM YYYY"
    theme:
      light:
        - cosmo
        - mozilla.scss
    css: styles.css
    toc: false
    include-in-header:
      - text: <script data-goatcounter="https://marem.goatcounter.com/count" async src="//gc.zgo.at/count.js"></script>
execute: 
  freeze: auto
